<a href="https://colab.research.google.com/github/mallapureddykumith/EDA-PROJECT/blob/main/EDA_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = pd.read_csv("/content/adult.csv")
print(data)

       Age     Workclass       Final Weight  Education    EducationNum  \
0      39           State-gov      77516       Bachelors       13
1      50    Self-emp-not-inc      83311       Bachelors       13
2      38             Private     215646         HS-grad        9
3      53             Private     234721            11th        7
4      28             Private     338409       Bachelors       13
...    ...                ...           ...          ...           ...
32556  27             Private     257302      Assoc-acdm       12
32557  40             Private     154374         HS-grad        9
32558  58             Private     151910         HS-grad        9
32559  22             Private     201490         HS-grad        9
32560  52        Self-emp-inc     287927         HS-grad        9

         Marital Status         Occupation       Relationship    Race   \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

       Gender   Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male       2174           0             40         United-States
1         Male          0           0             13         United-States
2         Male          0           0             40         United-States
3         Male          0           0             40         United-States
4       Female          0           0             40                  Cuba
...        ...           ...           ...             ...             ...
32556   Female          0           0             38         United-States
32557     Male          0           0             40         United-States
32558   Female          0           0             40         United-States
32559     Male          0           0             20         United-States
32560   Female      15024           0             40         United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]

In [ ]:
## Understanding the dataset
# Display the first 5 rows of the dataset
print(data.head())
# Display information about columns, data types, non-null values, and memory usage
print(data.info())
# Display statistical summary of numerical columns
print(data.describe())
# Display the names of all columns in the dataset
data.columns
# Display the last 5 rows of the dataset
data.tail()
# Display the number of rows and columns in the dataset
data.shape
# Display the number of non-missing values in each column
data.count()

   Age          Workclass  Final Weight   Education  EducationNum  \
0   39          State-gov         77516   Bachelors            13
1   50   Self-emp-not-inc         83311   Bachelors            13
2   38            Private        215646     HS-grad             9
3   53            Private        234721        11th             7
4   28            Private        338409   Bachelors            13

        Marital Status          Occupation    Relationship    Race   Gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   Capital Gain  capital loss  Hours per Week  Native Country  Income
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
4             0             0              40            Cuba   <=50K
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             32561 non-null  int64
 1   Workclass       32561 non-null  object
 2   Final Weight    32561 non-null  int64
 3   Education       32561 non-null  object
 4   EducationNum    32561 non-null  int64
 5   Marital Status  32561 non-null  object
 6   Occupation      32561 non-null  object
 7   Relationship    32561 non-null  object
 8   Race            32561 non-null  object
 9   Gender          32561 non-null  object
 10  Capital Gain    32561 non-null  int64
 11  capital loss    32561 non-null  int64
 12  Hours per Week  32561 non-null  int64
 13  Native Country  32561 non-null  object
 14  Income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None
                Age  Final Weight  EducationNum  Capital Gain  capital loss  \
count  32561.000000  3.256100e+04  32561.000000  32561.000000  32561.000000
mean      38.581647  1.897784e+05     10.080679   1077.648844     87.303830
std       13.640433  1.055500e+05      2.572720   7385.292085    402.960219
min       17.000000  1.228500e+04      1.000000      0.000000      0.000000
25%       28.000000  1.178270e+05      9.000000      0.000000      0.000000
50%       37.000000  1.783560e+05     10.000000      0.000000      0.000000
75%       48.000000  2.370510e+05     12.000000      0.000000      0.000000
max       90.000000  1.484705e+06     16.000000  99999.000000   4356.000000

       Hours per Week
count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000

Age               32561
Workclass         32561
Final Weight      32561
Education         32561
EducationNum      32561
Marital Status    32561
Occupation        32561
Relationship      32561
Race              32561
Gender            32561
Capital Gain      32561
capital loss      32561
Hours per Week    32561
Native Country    32561
Income            32561
dtype: int64

In [ ]:
## viewing and filtering
#1select and display only the age column from the dataset
df = pd.DataFrame(data)
print(df)
print(df["Age"])
print("________________________________________")
#2select the age, education, occupation, and income columns
print(df[["Age","Education","Occupation","Income"]])
print("________________________________________")
#3display the first 10 rows using iloc
print(df.iloc[10])
#4select rows 10 to 20 and display only the age and education columns
print(df.iloc[10:20][["Age","Education"]])
#5filter and display all the people whose age is greater than 500
print(df[df['Age'] > 50])
#6filter and display all the people whose income is >50k
print(df[df['Income'] == '>50K'])
print(d)
#7filter people whose age is greater than 40 and hours per week is greater than 20
print(df[(df['Age'] > 40) &(df['Hours per Week'] > 40)])
#8 filter people whose education is either bachelors or masters using isin()
print(df[df['Education'].isin([' Bachelors', 'Masters']) ])
#9find the mean, median, minimum, and max age of people in the dataset
print(df['Age'].agg(['mean','median','min','max']))
#10 find the standard deviation of age and hours-per-week
print(df[['Age', 'Hours per Week']].agg(['std']))
#11 use describe() to generate the statistical summary of all numerical columns
print(df.select_dtypes(include='number').agg(['count','mean','median','min','max','std']))
#12find the number of unique values in the education column and display thier frequesency using value_counts
print("Unique Education Values:",df['Education'].nunique())
print(df['Education'].value_counts())
#13 find the number of people in each income category using value_count
print(df['Income'].value_counts())
#14calculate the percentage of people belonging to each income category
print(df['Income'].value_counts(normalize=True ) * 100)
#15Find the average hours-per-week of people whose income is >50K
print(df[df['Income'] == '>50K']['Hours per Week'].agg(['count','mean','median','min','max','std']))
#16Find the average age of people whose education is Bachelors.
print(df[df['Education'] == ' Bachelors']['Age'].agg(['count', 'mean', 'median', 'min', 'max', 'std']))
#17Find the youngest and oldest person in the dataset.
print(df['Age'].agg(['min','max']))
#18Calculate the correlation between the numerical columns using corr().
print(df.corr(numeric_only=True))
#19Find the most common value (mode) of the education and occupation columns
print(df[['Age', 'Hours per Week']].corr())
print("Education Mode:",df['Education'].mode()[0])
print("Occupation Mode:",df['Occupation'].mode()[0])

       Age     Workclass       Final Weight  Education    EducationNum  \
0      39           State-gov      77516       Bachelors       13
1      50    Self-emp-not-inc      83311       Bachelors       13
2      38             Private     215646         HS-grad        9
3      53             Private     234721            11th        7
4      28             Private     338409       Bachelors       13
...    ...                ...           ...          ...           ...
32556  27             Private     257302      Assoc-acdm       12
32557  40             Private     154374         HS-grad        9
32558  58             Private     151910         HS-grad        9
32559  22             Private     201490         HS-grad        9
32560  52        Self-emp-inc     287927         HS-grad        9

         Marital Status         Occupation       Relationship    Race   \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

       Gender   Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male       2174           0             40         United-States
1         Male          0           0             13         United-States
2         Male          0           0             40         United-States
3         Male          0           0             40         United-States
4       Female          0           0             40                  Cuba
...        ...           ...           ...             ...             ...
32556   Female          0           0             38         United-States
32557     Male          0           0             40         United-States
32558   Female          0           0             40         United-States
32559     Male          0           0             20         United-States
32560   Female      15024           0             40         United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]
0        39
1        50
2        38
3        53
4        28
         ..
32556    27
32557    40
32558    58
32559    22
32560    52
Name: Age, Length: 32561, dtype: int64
________________________________________
       Age  Education        Occupation      Income
0      39     Bachelors        Adm-clerical   <=50K
1      50     Bachelors     Exec-managerial   <=50K
2      38       HS-grad   Handlers-cleaners   <=50K
3      53          11th   Handlers-cleaners   <=50K
4      28     Bachelors      Prof-specialty   <=50K
...    ...          ...                 ...     ...
32556  27    Assoc-acdm        Tech-support   <=50K
32557  40       HS-grad   Machine-op-inspct    >50K
32558  58       HS-grad        Adm-clerical   <=50K
32559  22       HS-grad        Adm-clerical   <=50K
32560  52       HS-grad     Exec-managerial    >50K

[32561 rows x 4 columns]
________________________________________
Age                                37
Workclass                     Private
Final Weight                   280464
Education                Some-college
EducationNum                       10
Marital Status     Married-civ-spouse
Occupation            Exec-managerial
Relationship                  Husband
Race                            Black
Gender                           Male
Capital Gain                        0
capital loss                        0
Hours per Week                     80
Native Country          United-States
Income                           >50K
Name: 10, dtype: object
    Age   Education
10  37    Some-college
11  30       Bachelors
12  23       Bachelors
13  32      Assoc-acdm
14  40       Assoc-voc
15  34         7th-8th
16  25         HS-grad
17  32         HS-grad
18  38            11th
19  43         Masters
       Age     Workclass       Final Weight   Education    EducationNum  \
3      53             Private     234721             11th        7
7      52    Self-emp-not-inc     209642          HS-grad        9
21     54             Private     302146          HS-grad        9
24     59             Private     109015          HS-grad        9
25     56           Local-gov     216851        Bachelors       13
...    ...                ...           ...           ...           ...
32542  72                   ?     129912          HS-grad        9
32548  65    Self-emp-not-inc      99359      Prof-school       15
32554  53             Private     321865          Masters       14
32558  58             Private     151910          HS-grad        9
32560  52        Self-emp-inc     287927          HS-grad        9

         Marital Status         Occupation       Relationship    Race   \
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
7       Married-civ-spouse     Exec-managerial         Husband   White
21               Separated       Other-service       Unmarried   Black
24                Divorced        Tech-support       Unmarried   White
25      Married-civ-spouse        Tech-support         Husband   White
...                    ...                 ...             ...     ...
32542   Married-civ-spouse                   ?         Husband   White
32548        Never-married      Prof-specialty   Not-in-family   White
32554   Married-civ-spouse     Exec-managerial         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

       Gender   Capital Gain  capital loss  Hours per Week  Native Country  \
3         Male          0           0             40         United-States
7         Male          0           0             45         United-States
21      Female          0           0             20         United-States
24      Female          0           0             40         United-States
25        Male          0           0             40         United-States
...        ...           ...           ...             ...             ...
32542     Male          0           0             25         United-States
32548     Male       1086           0             60         United-States
32554     Male          0           0             40         United-States
32558   Female          0           0             40         United-States
32560   Female      15024           0             40         United-States

       Income
3       <=50K
7        >50K
21      <=50K
24      <=50K
25       >50K
...       ...
32542   <=50K
32548   <=50K
32554    >50K
32558   <=50K
32560    >50K

[6460 rows x 15 columns]
Empty DataFrame
Columns: [Age, Workclass, Final Weight, Education, EducationNum, Marital Status, Occupation, Relationship, Race, Gender, Capital Gain, capital loss, Hours per Week, Native Country, Income]
Index: []
0        False
1        False
2        False
3         True
4        False
         ...
32556    False
32557    False
32558     True
32559    False
32560     True
Length: 32561, dtype: bool
       Age     Workclass       Final Weight   Education     EducationNum  \
7      52    Self-emp-not-inc     209642           HS-grad        9
19     43    Self-emp-not-inc     292175           Masters       14
27     54                   ?     180211      Some-college       10
52     47             Private      51835       Prof-school       15
53     50         Federal-gov     251585         Bachelors       13
...    ...                ...           ...            ...           ...
32533  54             Private     337992         Bachelors       13
32543  45           Local-gov     119199        Assoc-acdm       12
32548  65    Self-emp-not-inc      99359       Prof-school       15
32550  43    Self-emp-not-inc      27242      Some-college       10
32552  43             Private      84661         Assoc-voc       11

         Marital Status        Occupation      Relationship   \
7       Married-civ-spouse   Exec-managerial         Husband
19                Divorced   Exec-managerial       Unmarried
27      Married-civ-spouse                 ?         Husband
52      Married-civ-spouse    Prof-specialty            Wife
53                Divorced   Exec-managerial   Not-in-family
...                    ...               ...             ...
32533   Married-civ-spouse   Exec-managerial         Husband
32543             Divorced    Prof-specialty       Unmarried
32548        Never-married    Prof-specialty   Not-in-family
32550   Married-civ-spouse      Craft-repair         Husband
32552   Married-civ-spouse             Sales         Husband

              Race          Gender   Capital Gain  capital loss  \
7                    White     Male         0             0
19                   White   Female         0             0
27      Asian-Pac-Islander     Male         0             0
52                   White   Female         0          1902
53                   White     Male         0             0
...                    ...      ...           ...           ...
32533   Asian-Pac-Islander     Male         0             0
32543                White   Female         0             0
32548                White     Male      1086             0
32550                White     Male         0             0
32552                White     Male         0             0

       Hours per Week  Native Country  Income
7            45         United-States    >50K
19           45         United-States    >50K
27           60                 South    >50K
52           60              Honduras    >50K
53           55         United-States    >50K
...               ...             ...     ...
32533        50                 Japan    >50K
32543        48         United-States   <=50K
32548        60         United-States   <=50K
32550        50         United-States   <=50K
32552        45         United-States   <=50K

[4323 rows x 15 columns]
       Age     Workclass       Final Weight  Education   EducationNum  \
0      39           State-gov      77516      Bachelors       13
1      50    Self-emp-not-inc      83311      Bachelors       13
4      28             Private     338409      Bachelors       13
9      42             Private     159449      Bachelors       13
11     30           State-gov     141297      Bachelors       13
...    ...                ...           ...         ...           ...
32530  35                   ?     320084      Bachelors       13
32531  30                   ?      33811      Bachelors       13
32533  54             Private     337992      Bachelors       13
32536  34             Private     160216      Bachelors       13
32538  38             Private     139180      Bachelors       13

         Marital Status        Occupation      Relationship   \
0            Never-married      Adm-clerical   Not-in-family
1       Married-civ-spouse   Exec-managerial         Husband
4       Married-civ-spouse    Prof-specialty            Wife
9       Married-civ-spouse   Exec-managerial         Husband
11      Married-civ-spouse    Prof-specialty         Husband
...                    ...               ...             ...
32530   Married-civ-spouse                 ?            Wife
32531        Never-married                 ?   Not-in-family
32533   Married-civ-spouse   Exec-managerial         Husband
32536        Never-married   Exec-managerial   Not-in-family
32538             Divorced    Prof-specialty       Unmarried

              Race          Gender   Capital Gain  capital loss  \
0                    White     Male       2174           0
1                    White     Male          0           0
4                    Black   Female          0           0
9                    White     Male       5178           0
11      Asian-Pac-Islander     Male          0           0
...                    ...      ...           ...           ...
32530                White   Female          0           0
32531   Asian-Pac-Islander   Female          0           0
32533   Asian-Pac-Islander     Male          0           0
32536                White   Female          0           0
32538                Black   Female      15020           0

       Hours per Week  Native Country  Income
0            40         United-States   <=50K
1            13         United-States   <=50K
4            40                  Cuba   <=50K
9            40         United-States    >50K
11           40                 India    >50K
...               ...             ...     ...
32530        55         United-States    >50K
32531        99         United-States   <=50K
32533        50                 Japan    >50K
32536        55         United-States    >50K
32538        45         United-States    >50K

[5355 rows x 15 columns]
mean      38.581647
median    37.000000
min       17.000000
max       90.000000
Name: Age, dtype: float64
        Age     Hours per Week
std  13.640433     12.347429
             Age      Final Weight  EducationNum  Capital Gain  capital loss  \
count   32561.000000  3.256100e+04  32561.000000  32561.000000  32561.000000
mean       38.581647  1.897784e+05     10.080679   1077.648844     87.303830
median     37.000000  1.783560e+05     10.000000      0.000000      0.000000
min        17.000000  1.228500e+04      1.000000      0.000000      0.000000
max        90.000000  1.484705e+06     16.000000  99999.000000   4356.000000
std        13.640433  1.055500e+05      2.572720   7385.292085    402.960219

        Hours per Week
count    32561.000000
mean        40.437456
median      40.000000
min          1.000000
max         99.000000
std         12.347429
Unique Education Values: 16
Education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64
Income
<=50K    24720
>50K      7841
Name: count, dtype: int64
Income
<=50K    75.919044
>50K     24.080956
Name: proportion, dtype: float64
count     0.0
mean      NaN
median    NaN
min       NaN
max       NaN
std       NaN
Name: Hours per Week, dtype: float64
count     5355.000000
mean        38.904949
median      37.000000
min         19.000000
max         90.000000
std         11.912210
Name: Age, dtype: float64
min    17
max    90
Name: Age, dtype: int64
                   Age    Final Weight  EducationNum  Capital Gain  \
Age             1.000000   -0.076646      0.036527      0.077674
Final Weight   -0.076646    1.000000     -0.043195      0.000432
EducationNum    0.036527   -0.043195      1.000000      0.122630
Capital Gain    0.077674    0.000432      0.122630      1.000000
capital loss    0.057775   -0.010252      0.079923     -0.031615
Hours per Week  0.068756   -0.018768      0.148123      0.078409

                capital loss  Hours per Week
Age               0.057775       0.068756
Final Weight     -0.010252      -0.018768
EducationNum      0.079923       0.148123
Capital Gain     -0.031615       0.078409
capital loss      1.000000       0.054256
Hours per Week    0.054256       1.000000
                   Age    Hours per Week
Age             1.000000     0.068756
Hours per Week  0.068756     1.000000
Education Mode:  HS-grad
Occupation Mode:  Prof-specialty

In [ ]:
# Cleaning
# EDA-4: Identify NaN values
import pandas as pd
# Identify null values
print(df.isnull())
# Count null values in each column
print(df.isnull().sum())
print("___________________________________________________________________________")
# Replace " ?" with NaN
df = df.replace(" ?", None)
# Check missing values after replacement
print(df.isna().sum())
print("___________________________________________________________________________")
# Fill missing values with a constant
print(df.fillna(0))
print("___________________________________________________________________________")
# Find the mean of numeric columns
print(df.mean(numeric_only=True))
print("___________________________________________________________________________")
# Find the median of numeric columns
print(df.median(numeric_only=True))
print("___________________________________________________________________________")
# Find the mode of each column
print(df.mode())
print("___________________________________________________________________________")
# Store the number of missing values
data = df.isna().sum()
print(data)

         Age  Workclass  Final Weight  Education  EducationNum  \
0      False      False         False      False         False
1      False      False         False      False         False
2      False      False         False      False         False
3      False      False         False      False         False
4      False      False         False      False         False
...      ...        ...           ...        ...           ...
32556  False      False         False      False         False
32557  False      False         False      False         False
32558  False      False         False      False         False
32559  False      False         False      False         False
32560  False      False         False      False         False

       Marital Status  Occupation  Relationship   Race  Gender  Capital Gain  \
0               False       False         False  False   False         False
1               False       False         False  False   False         False
2               False       False         False  False   False         False
3               False       False         False  False   False         False
4               False       False         False  False   False         False
...               ...         ...           ...    ...     ...           ...
32556           False       False         False  False   False         False
32557           False       False         False  False   False         False
32558           False       False         False  False   False         False
32559           False       False         False  False   False         False
32560           False       False         False  False   False         False

       capital loss  Hours per Week  Native Country  Income
0             False           False           False   False
1             False           False           False   False
2             False           False           False   False
3             False           False           False   False
4             False           False           False   False
...             ...             ...             ...     ...
32556         False           False           False   False
32557         False           False           False   False
32558         False           False           False   False
32559         False           False           False   False
32560         False           False           False   False

[32537 rows x 15 columns]
Age               0
Workclass         0
Final Weight      0
Education         0
EducationNum      0
Marital Status    0
Occupation        0
Relationship      0
Race              0
Gender            0
Capital Gain      0
capital loss      0
Hours per Week    0
Native Country    0
Income            0
dtype: int64
___________________________________________________________________________
Age                  0
Workclass         1836
Final Weight         0
Education            0
EducationNum         0
Marital Status       0
Occupation        1843
Relationship         0
Race                 0
Gender               0
Capital Gain         0
capital loss         0
Hours per Week       0
Native Country     582
Income               0
dtype: int64
___________________________________________________________________________
       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32537 rows x 15 columns]
___________________________________________________________________________
Age                   38.585549
Final Weight      189780.848511
EducationNum          10.081815
Capital Gain        1078.443741
capital loss          87.368227
Hours per Week        40.440329
dtype: float64
___________________________________________________________________________
Age                   37.0
Final Weight      178356.0
EducationNum          10.0
Capital Gain           0.0
capital loss           0.0
Hours per Week        40.0
dtype: float64
___________________________________________________________________________
    Age Workclass  Final Weight Education  EducationNum       Marital Status  \
0  36.0   Private        123011   HS-grad           9.0   Married-civ-spouse
1   NaN       NaN        164190       NaN           NaN                  NaN
2   NaN       NaN        203488       NaN           NaN                  NaN

        Occupation Relationship    Race Gender  Capital Gain  capital loss  \
0   Prof-specialty      Husband   White   Male           0.0           0.0
1              NaN          NaN     NaN    NaN           NaN           NaN
2              NaN          NaN     NaN    NaN           NaN           NaN

   Hours per Week  Native Country  Income
0            40.0   United-States   <=50K
1             NaN             NaN     NaN
2             NaN             NaN     NaN
___________________________________________________________________________
Age                  0
Workclass         1836
Final Weight         0
Education            0
EducationNum         0
Marital Status       0
Occupation        1843
Relationship         0
Race                 0
Gender               0
Capital Gain         0
capital loss         0
Hours per Week       0
Native Country     582
Income               0
dtype: int64

In [ ]:
# Identify duplicate rows
print(df.duplicated())
# Count the number of duplicate rows
print(df.duplicated().sum())
print("___________________________________________________________________________")
# Display only duplicate rows
print(df[df.duplicated()])
print("___________________________________________________________________________")
# Remove duplicate rows
df = df.drop_duplicates()
# Check again after removing duplicates
print(df.duplicated().sum())
# Display the cleaned DataFrame
print(df)

0        False
1        False
2        False
3        False
4        False
         ...
32556    False
32557    False
32558    False
32559    False
32560    False
Length: 32537, dtype: bool
0
___________________________________________________________________________
Empty DataFrame
Columns: [Age, Workclass, Final Weight, Education, EducationNum, Marital Status, Occupation, Relationship, Race, Gender, Capital Gain, capital loss, Hours per Week, Native Country, Income]
Index: []
___________________________________________________________________________
0
       Age     Workclass       Final Weight  Education    EducationNum  \
0      39           State-gov      77516       Bachelors       13
1      50    Self-emp-not-inc      83311       Bachelors       13
2      38             Private     215646         HS-grad        9
3      53             Private     234721            11th        7
4      28             Private     338409       Bachelors       13
...    ...                ...           ...          ...           ...
32556  27             Private     257302      Assoc-acdm       12
32557  40             Private     154374         HS-grad        9
32558  58             Private     151910         HS-grad        9
32559  22             Private     201490         HS-grad        9
32560  52        Self-emp-inc     287927         HS-grad        9

         Marital Status         Occupation       Relationship    Race   \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

       Gender   Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male       2174           0             40         United-States
1         Male          0           0             13         United-States
2         Male          0           0             40         United-States
3         Male          0           0             40         United-States
4       Female          0           0             40                  Cuba
...        ...           ...           ...             ...             ...
32556   Female          0           0             38         United-States
32557     Male          0           0             40         United-States
32558   Female          0           0             40         United-States
32559     Male          0           0             20         United-States
32560   Female      15024           0             40         United-States

       Income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32537 rows x 15 columns]

In [ ]:
#Calculate the first quartile (Q1), third quartile (Q3), and interquartile range (IQR) of Age.
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3-Q1
print("Q1:",Q1)
print("Q3:",Q3)
print("IQR:",IQR)

Q1: 28.0
Q3: 48.0
IQR: 20.0

In [ ]:
# Identifying the Age values outside the IQR bounds and count them as potential outliers.
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)

IQR = Q3-Q1
lower = Q1 - 1.5 * IQR
UPPER = Q3 + 1.5 * IQR
iqr_outliers = df[
    (df['Age']< lower) |
    (df['Age']> UPPER)
]
print("IQR Outliers:", len(iqr_outliers))

IQR Outliers: 143

In [ ]:
import pandas as pd
from scipy.stats import zscore
# Calculating the z-scores for Age and identify observations with an absolute z-score greater than 3 as outliers.
df['Age_zscore'] = zscore(df['Age'])
z_outliers = df[df['Age_zscore'].abs()>3]
print("z-score outliers:", len(z_outliers))

z-score outliers: 120

In [ ]:
#3. z_score trimming
df_trimmed = df[df['Age_zscore'].abs() <=3]
print(df_trimmed)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       50   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       53            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   58            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   52       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income  Age_zscore
0       <=50K    0.030390
1       <=50K    0.836973
2       <=50K   -0.042936
3       <=50K    1.056950
4       <=50K   -0.776193
...       ...         ...
32556   <=50K   -0.849519
32557    >50K    0.103716
32558   <=50K    1.423579
32559   <=50K   -1.216148
32560    >50K    0.983625

[32417 rows x 16 columns]

In [ ]:
#4.winsorization
from scipy.stats.mstats import winsorize
df['Age_winsorized'] = winsorize(
    df['Age'],
    limits=[0,0.3])
print(df.head())

   Age          Workclass  Final Weight   Education  EducationNum  \
0   39          State-gov         77516   Bachelors            13
1   45   Self-emp-not-inc         83311   Bachelors            13
2   38            Private        215646     HS-grad             9
3   45            Private        234721        11th             7
4   28            Private        338409   Bachelors            13

        Marital Status          Occupation    Relationship    Race   Gender  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   Capital Gain  capital loss  Hours per Week  Native Country  Income  \
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
4             0             0              40            Cuba   <=50K

   Age_zscore  Age_winsorized
0    0.030390              39
1    0.836973              45
2   -0.042936              38
3    1.056950              45
4   -0.776193              28

In [ ]:
# Calculating the Q1, Q3, and IQR for EducationNum to understand its spread and detect potential outliers.
Q1 = df['EducationNum'].quantile(0.25)
Q3 = df['EducationNum'].quantile(0.75)
IQR = Q3-Q1
print("Q1:",Q1)
print("Q3:",Q3)
print("IQR:",IQR)

Q1: 9.0
Q3: 12.0
IQR: 3.0

In [ ]:
# Calculate the lower and upper IQR bounds to identify potential outliers in EducationNum.
Q1 = df['EducationNum'].quantile(0.25)
Q3 = df['EducationNum'].quantile(0.75)
IQR = Q3-Q1
lower_bound =(Q1 - 1.5 * IQR)
upper_bound =(Q3 + 1.5 * IQR)
print(lower_bound)
print(upper_bound)

4.5
16.5

In [ ]:
# Calculate z-scores for EducationNum and identify values with an absolute z-score greater than 3 as outliers.
import pandas as pd
from scipy.stats import zscore
df['EducationNum_zscore'] = zscore(df['EducationNum'])

z_outliers = df[
    df['EducationNum_zscore'].abs()>3
]
print("z-score outliers:", len(z_outliers))

z-score outliers: 216

In [ ]:
# Remove rows with an absolute EducationNum z-score greater than 10 and display the trimmed dataset.
from scipy.stats import zscore
df['EducationNum_zscore'] = zscore(df['EducationNum'])
df_trimmed = df[df['EducationNum_zscore'].abs() <=10]
print(df_trimmed)

       Age          Workclass  Final Weight    Education  EducationNum  \
0       39          State-gov         77516    Bachelors            13
1       45   Self-emp-not-inc         83311    Bachelors            13
2       38            Private        215646      HS-grad             9
3       45            Private        234721         11th             7
4       28            Private        338409    Bachelors            13
...    ...                ...           ...          ...           ...
32556   27            Private        257302   Assoc-acdm            12
32557   40            Private        154374      HS-grad             9
32558   45            Private        151910      HS-grad             9
32559   22            Private        201490      HS-grad             9
32560   45       Self-emp-inc        287927      HS-grad             9

            Marital Status          Occupation    Relationship    Race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

        Gender  Capital Gain  capital loss  Hours per Week  Native Country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       Income  Age_zscore  Age_winsorized  EducationNum_zscore
0       <=50K    0.030390              39             1.134777
1       <=50K    0.836973              45             1.134777
2       <=50K   -0.042936              38            -0.420679
3       <=50K    1.056950              45            -1.198407
4       <=50K   -0.776193              28             1.134777
...       ...         ...             ...                  ...
32556   <=50K   -0.849519              27             0.745913
32557    >50K    0.103716              40            -0.420679
32558   <=50K    1.423579              45            -0.420679
32559   <=50K   -1.216148              22            -0.420679
32560    >50K    0.983625              45            -0.420679

[32537 rows x 18 columns]

In [ ]:
import matplotlib.pyplot as plt
#Age Distribution
#Histogram
plt.figure(figsize=(8, 5))
plt.hist(df['Age'], bins=20, color='skyblue', edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

In [ ]:
#Education Number Distribution
#Bar Chart
education_counts = df['EducationNum'].value_counts().sort_index()
plt.figure(figsize=(8, 5))
plt.bar(education_counts.index, education_counts.values, color='orange', edgecolor='black')
plt.title('Distribution of Education Number')
plt.xlabel('Education Number')
plt.ylabel('Count')
plt.show()

In [ ]:
# Age vs Hours per Week
#Scatter Plot
plt.figure(figsize=(8, 5))
plt.scatter(df['Age'], df['Hours per Week'], alpha=0.3, color='blue')
plt.title('Age vs Hours per Week')
plt.xlabel('Age')
plt.ylabel('Hours per Week')
plt.show()

In [ ]:
#Income Distribution
#Pie Chart
income_counts = df['Income'].value_counts()
plt.figure(figsize=(7, 5))
plt.pie(income_counts.values,labels=income_counts.index,autopct='%1.1f%%')
plt.title('Income Distribution')
plt.show()

In [ ]:
#Hours per Week Distribution
#Violin Plot
plt.figure(figsize=(8, 5))
plt.violinplot(df['Hours per Week'])
plt.title('Hours Worked per Week')
plt.ylabel('Hours per Week')
plt.show()

In [ ]:
#autoviz tool
import pandas as pd
#!pip install autoviz
from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()
data = pd.read_csv("adult.csv")
AV.AutoViz(
    filename="adult.csv",
    sep=",",
    depVar="Income",
    dfte=data)

Shape of your Data Set loaded: (32561, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  6
    Number of String-Categorical Columns =  7
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    14 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Binary_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 24 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

Total Number of Scatter Plots = 21
All Plots done
Time to run AutoViz = 12 seconds

 ###################### AUTO VISUALIZATION Completed ########################

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1

In [ ]:
AV.AutoViz(
    filename="adult.csv",
    sep=",",
    depVar="Income",
    dfte=data,
    chart_format="png")

Shape of your Data Set loaded: (32561, 15)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  0
    Number of Integer-Categorical Columns =  6
    Number of String-Categorical Columns =  7
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  1
    Number of Numeric-Boolean Columns =  0
    Number of Discrete String Columns =  0
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  0
    Number of Columns to Delete =  0
    14 Predictors classified...
        No variables removed since no ID or low-information variables found in data set

################ Binary_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 24 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

Total Number of Scatter Plots = 21
All Plots done
Time to run AutoViz = 12 seconds

 ###################### AUTO VISUALIZATION Completed ########################

,Age,Workclass,Final Weight,Education,EducationNum,Marital Status,Occupation,Relationship,Race,Gender,Capital Gain,capital loss,Hours per Week,Native Country,Income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,0
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,0
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,0
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,1